"use client";
import {useEffect,useMemo,useState} from "react";
import {Activity,ClipboardCheck,FileText,LogOut,Mic,ShieldCheck,Sparkles,X} from "lucide-react";
import {departments,Department} from "@/lib/data";
type CoreState="standby"|"listening"|"processing"|"speaking";
const stateText:Record<CoreState,string>={standby:"STANDBY",listening:"LISTENING",processing:"PROCESSING",speaking:"SPEAKING"};
export default function CapriceApp(){
 const [logged,setLogged]=useState(false),[name,setName]=useState("Owner");
 const [state,setState]=useState<CoreState>("standby"),[selected,setSelected]=useState<Department|null>(null),[hse,setHse]=useState(false),[toast,setToast]=useState("");
 const nodes=useMemo(()=>departments.map((d,i)=>({...d,a:(i/departments.length)*Math.PI*2})),[]);
 useEffect(()=>{if(!toast)return;const t=setTimeout(()=>setToast(""),2500);return()=>clearTimeout(t)},[toast]);
 const cycle=()=>setState(s=>s==="standby"?"processing":s==="processing"?"speaking":"standby");
 const voice=()=>{setState("listening");const SR=(window as any).SpeechRecognition||(window as any).webkitSpeechRecognition;if(!SR){setToast("Speech recognition is unavailable; simulation started.");setTimeout(()=>setState("processing"),1200);setTimeout(()=>setState("speaking"),2300);setTimeout(()=>setState("standby"),4200);return}const r=new SR();r.lang="en-US";r.interimResults=false;r.onresult=(e:any)=>{setToast(`Heard: ${e.results[0][0].transcript}`);setState("processing");setTimeout(()=>setState("speaking"),900);setTimeout(()=>setState("standby"),2800)};r.onerror=()=>{setToast("Voice session ended safely.");setState("standby")};r.start()};
 if(!logged)return <Login name={name} setName={setName} onLogin={()=>setLogged(true)}/>;
 return <main className="app-shell">
  <header className="topbar"><div><div className="eyebrow">SECURE ONLINE-FIRST CORE NEURAL SYSTEM</div><h1>CAPRICE <span>V6.1</span></h1></div><div className="top-actions"><div className="secure"><ShieldCheck size={15}/> DEVELOPMENT MODE</div><button className="ghost" onClick={()=>setLogged(false)}><LogOut size={15}/> Sign out</button></div></header>
  <section className="command-strip"><div><strong>Welcome, {name}</strong><span>Cloud-authoritative mock environment</span></div><div className="health"><i/> All prototype modules operational</div></section>
  <section className="world" aria-label="CAPRICE department network">
   <div className={`core ${state}`} onClick={cycle} role="button" tabIndex={0} aria-label="Cycle CAPRICE state"><div className="core-halo"/><div className="core-ring r1"/><div className="core-ring r2"/><div className="core-ball"><Sparkles/><b>CAPRICE</b><small>{stateText[state]}</small></div></div>
   <svg className="links" viewBox="0 0 1000 680" preserveAspectRatio="none" aria-hidden="true">{nodes.map((n,i)=>{const x=500+Math.cos(n.a)*390,y=340+Math.sin(n.a)*260;return <line key={i} x1="500" y1="340" x2={x} y2={y}/>})}</svg>
   {nodes.map((n,i)=>{const x=50+Math.cos(n.a)*39,y=50+Math.sin(n.a)*38;return <button key={n.key} className="dept-node" style={{left:`${x}%`,top:`${y}%`,"--c":n.color} as React.CSSProperties} onClick={()=>n.key==="hse"?setHse(true):setSelected(n)}><span>{n.short}</span><em>{n.name}</em></button>})}
  </section>
  <footer className="statusbar"><div className="wave">{Array.from({length:26}).map((_,i)=><i key={i} style={{animationDelay:`${i*.05}s`}}/>)}</div><button onClick={voice}><Mic size={18}/>{state==="listening"?"Listening…":"Push to talk"}</button><div>{stateText[state]} · ONLINE SOURCE OF TRUTH</div></footer>
  {selected&&<DepartmentPanel d={selected} close={()=>setSelected(null)} notify={setToast}/>} {hse&&<HseWorkspace close={()=>setHse(false)} notify={setToast}/>} {toast&&<div className="toast">{toast}</div>}
 </main>
}
function Login({name,setName,onLogin}:{name:string;setName:(v:string)=>void;onLogin:()=>void}){return <main className="login"><div className="login-card"><div className="login-orb">C</div><div className="eyebrow">CAPRICE V6.1</div><h1>Development Access</h1><p>This prototype uses a local development login and mock data only.</p><label>Display name<input value={name} onChange={e=>setName(e.target.value)}/></label><button onClick={onLogin}>Enter secure prototype</button><small>No credentials are transmitted or stored.</small></div></main>}
function DepartmentPanel({d,close,notify}:{d:Department;close:()=>void;notify:(s:string)=>void}){return <div className="overlay"><section className="panel" style={{"--c":d.color} as React.CSSProperties}><button className="close" onClick={close}><X/></button><div className="panel-head"><Activity/><div><div className="eyebrow">DEPARTMENT OVERVIEW</div><h2>{d.name}</h2><p>{d.role}</p></div></div><div className="metrics">{d.metrics.map(m=><div key={m}>{m}</div>)}</div><h3>Available prototype actions</h3><div className="action-grid">{d.actions.map(a=><button key={a} onClick={()=>notify(`${a}: prototype action recorded`)}>{a}</button>)}</div><div className="audit">Mock action only · No external system changes · Audit preview enabled</div></section></div>}
function HseWorkspace({close,notify}:{close:()=>void;notify:(s:string)=>void}){const [tab,setTab]=useState("Observation");const tabs=["Observation","DOB Modelling","Corrective Actions","Approval","KPIs","Documents"];return <div className="overlay"><section className="panel hse-panel"><button className="close" onClick={close}><X/></button><div className="panel-head"><ClipboardCheck/><div><div className="eyebrow">HSE MVP WORKSPACE</div><h2>{tab}</h2><p>Structured mock workflow with owner, status, evidence and audit preview.</p></div></div><nav className="tabs">{tabs.map(t=><button className={tab===t?"active":""} onClick={()=>setTab(t)} key={t}>{t}</button>)}</nav>{tab==="KPIs"?<div className="kpis"><div><b>92%</b>Close-out rate</div><div><b>14</b>Open actions</div><div><b>3</b>Draft records</div></div>:tab==="Documents"?<div className="drop"><FileText/><b>Upload / OCR placeholder</b><span>Files remain local in this frontend prototype.</span><input type="file" onChange={()=>notify("Document selected for mock validation")}/></div>:<form className="hse-form" onSubmit={e=>{e.preventDefault();notify(`${tab} draft saved locally`)}}><label>Title<input required placeholder={`${tab} title`}/></label><label>Description<textarea required placeholder="Enter controlled mock data"/></label><div className="form-row"><label>Owner<input defaultValue="Development Owner"/></label><label>Due date<input type="date"/></label></div><label>Evidence reference<input placeholder="Optional mock reference"/></label><button type="submit">Save mock draft</button></form>}</section></div>}
