export type Department={key:string;name:string;short:string;role:string;color:string;status:"online"|"standby";metrics:string[];actions:string[]};
export const departments:Department[]=[
{key:"executive",name:"Executive Command",short:"EXEC",role:"Briefings, approvals and cross-department routing",color:"#2de2e6",status:"online",metrics:["6 approvals pending","Morning brief ready","12 active workflows"],actions:["Open approval queue","Generate executive brief"]},
{key:"hse",name:"HSE",short:"HSE",role:"Observations, DOB modelling, corrective actions and KPIs",color:"#26d6a3",status:"online",metrics:["14 open actions","92% close-out rate","3 drafts awaiting review"],actions:["New observation","Open HSE workspace"]},
{key:"business",name:"Business & Commerce",short:"BIZ",role:"Businesses, products, inventory, orders and customers",color:"#f6b84a",status:"online",metrics:["Business 001: Ruth Jewels","28 orders active","4 low-stock alerts"],actions:["View orders","Add product"]},
{key:"productivity",name:"Productivity",short:"PROD",role:"Email, calendar, tasks and commitments",color:"#76b9ff",status:"online",metrics:["8 action items","Next briefing 09:00","5 reminders due"],actions:["Open daily plan","Review commitments"]},
{key:"finance",name:"Finance",short:"FIN",role:"Budgets, cashflow, forecasts and governance",color:"#f4d35e",status:"online",metrics:["Cash position stable","2 budget alerts","Forecast refreshed"],actions:["Open cashflow","Review alerts"]},
{key:"health",name:"Health",short:"HLTH",role:"Restricted records and reminders",color:"#ff7f9f",status:"standby",metrics:["Restricted workspace","No urgent reminders","Access controlled"],actions:["Open reminders"]},
{key:"security",name:"Security",short:"SEC",role:"Access, incidents, risks and audit review",color:"#ff6b6b",status:"online",metrics:["All services healthy","1 access review due","Audit stream active"],actions:["Review security","Open audit"]},
{key:"intelligence",name:"News & Market Intelligence",short:"INTEL",role:"Verified news, markets and economic events",color:"#9f8cff",status:"online",metrics:["7 tracked topics","Sources verified","Daily digest ready"],actions:["Open digest","Manage sources"]},
{key:"investment",name:"Investment",short:"INV",role:"Research, portfolio, risk and paper trading",color:"#b6e36b",status:"standby",metrics:["Paper mode only","5 watchlist items","Risk checks enabled"],actions:["Open watchlist","Review paper portfolio"]},
{key:"documents",name:"Documents",short:"DOCS",role:"Upload, OCR, validation and evidence",color:"#56cfe1",status:"online",metrics:["3 files processing","OCR queue clear","2 validation issues"],actions:["Upload document","Review issues"]},
{key:"voice",name:"Voice",short:"VOICE",role:"Push-to-talk commands and transcripts",color:"#00e5ff",status:"online",metrics:["Push-to-talk ready","Transcript confirmation on","Audit enabled"],actions:["Start voice session"]},
{key:"system",name:"System Operations",short:"OPS",role:"Agents, APIs, releases, incidents and costs",color:"#94a3b8",status:"online",metrics:["12/12 modules online","No active incident","Mock environment"],actions:["Open system health"]}
];
